spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3307/photo_app?useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: pawan132
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /mobile-app-ws
  port: 8080

tokenSecret: jf9i4jgu83nfl0
userController.authorizationHeader.description: Bearer JWT Token